project_id = "kxnzhrzfhoxibdzvikyj"

[functions.get-leaderboard]
verify_jwt = false

[functions.get-questions]
verify_jwt = false

[functions.submit-quiz]
verify_jwt = true

[functions.add-question]
verify_jwt = true
