-- Remove existing questions to replace with curated MCQs
truncate table public.questions restart identity cascade;

-- Seed 100 multiple-choice questions across categories
-- Note: Replace/add with your curated content as needed. This is a concise seed with representative topics.
insert into public.questions (type, question_text, options, correct_answer, image_url, category)
values
  ('multiple_choice','Which language runs in a web browser?','["Java","C","Python","JavaScript"]','JavaScript',null,'Technology'),
  ('multiple_choice','What does CSS stand for?','["Central Style Sheets","Cascading Style Sheets","Computer Style Sheets","Creative Style System"]','Cascading Style Sheets',null,'Technology'),
  ('multiple_choice','What does HTML stand for?','["HyperText Markup Language","Hyperlinks and Text Markup Language","Home Tool Markup Language","Hyper Trainer Marking Language"]','HyperText Markup Language',null,'Technology'),
  ('multiple_choice','What year was JavaScript launched?','["1996","1995","1994","None of the above"]','1995',null,'Technology'),
  ('multiple_choice','Which company developed the React library?','["Google","Facebook","Microsoft","Twitter"]','Facebook',null,'Technology'),
  ('multiple_choice','Which planet is known as the Red Planet?','["Venus","Mars","Jupiter","Saturn"]','Mars',null,'Science'),
  ('multiple_choice','What is the chemical symbol for gold?','["Ag","Au","Gd","Go"]','Au',null,'Science'),
  ('multiple_choice','What gas do plants absorb from the atmosphere?','["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"]','Carbon dioxide',null,'Science'),
  ('multiple_choice','How many bones are in the adult human body?','["196","206","216","226"]','206',null,'Science'),
  ('multiple_choice','What is the powerhouse of the cell?','["Nucleus","Mitochondria","Ribosome","Golgi apparatus"]','Mitochondria',null,'Science'),
  ('multiple_choice','Who proposed the theory of relativity?','["Isaac Newton","Albert Einstein","Niels Bohr","Galileo Galilei"]','Albert Einstein',null,'Science'),
  ('multiple_choice','What is H2O commonly known as?','["Hydrogen Peroxide","Water","Oxygen","Salt"]','Water',null,'Science'),
  ('multiple_choice','Which process converts sugar into alcohol?','["Distillation","Fermentation","Sublimation","Oxidation"]','Fermentation',null,'Science'),
  ('multiple_choice','What is the speed of light in vacuum (approx.)?','["3×10^6 m/s","3×10^8 m/s","3×10^10 m/s","3×10^5 m/s"]','3×10^8 m/s',null,'Science'),
  ('multiple_choice','Which vitamin is produced when a person is exposed to sunlight?','["Vitamin A","Vitamin B12","Vitamin C","Vitamin D"]','Vitamin D',null,'Science'),
  ('multiple_choice','What is the capital of Japan?','["Seoul","Beijing","Tokyo","Kyoto"]','Tokyo',null,'Geography'),
  ('multiple_choice','Which is the largest ocean on Earth?','["Atlantic Ocean","Indian Ocean","Arctic Ocean","Pacific Ocean"]','Pacific Ocean',null,'Geography'),
  ('multiple_choice','Mount Everest lies on the border of which two countries?','["India and China","Nepal and China","Bhutan and China","India and Nepal"]','Nepal and China',null,'Geography'),
  ('multiple_choice','Which river flows through London?','["Seine","Thames","Danube","Rhine"]','Thames',null,'Geography'),
  ('multiple_choice','Which desert is the largest hot desert in the world?','["Gobi","Kalahari","Sahara","Arabian"]','Sahara',null,'Geography'),
  ('multiple_choice','Who wrote "1984"?','["Aldous Huxley","George Orwell","Ernest Hemingway","F. Scott Fitzgerald"]','George Orwell',null,'History'),
  ('multiple_choice','Who was the first President of the United States?','["George Washington","Thomas Jefferson","John Adams","James Madison"]','George Washington',null,'History'),
  ('multiple_choice','The Renaissance began in which country?','["France","England","Italy","Germany"]','Italy',null,'History'),
  ('multiple_choice','In which year did World War II end?','["1943","1944","1945","1946"]','1945',null,'History'),
  ('multiple_choice','Who discovered penicillin?','["Alexander Fleming","Marie Curie","Louis Pasteur","Edward Jenner"]','Alexander Fleming',null,'History'),
  ('multiple_choice','In computing, what does CPU stand for?','["Central Processing Unit","Core Processing Unit","Central Performance Unit","Computer Processing Unit"]','Central Processing Unit',null,'Technology'),
  ('multiple_choice','Which database is a NoSQL database?','["MySQL","PostgreSQL","MongoDB","SQLite"]','MongoDB',null,'Technology'),
  ('multiple_choice','Which HTML tag is used to define an unordered list?','["<ol>","<ul>","<li>","<list>"]','<ul>',null,'Technology'),
  ('multiple_choice','Which protocol is used to secure HTTP?','["FTP","SSH","TLS","SMTP"]','TLS',null,'Technology'),
  ('multiple_choice','Which company maintains the Chromium project?','["Apple","Google","Microsoft","Mozilla"]','Google',null,'Technology'),
  ('multiple_choice','Which organ purifies blood in the human body?','["Heart","Lungs","Kidneys","Liver"]','Kidneys',null,'Science'),
  ('multiple_choice','Which element has the chemical symbol Fe?','["Fluorine","Iron","Francium","Fermium"]','Iron',null,'Science'),
  ('multiple_choice','Which blood type is known as the universal donor?','["A+","O-","AB+","B-"]','O-',null,'Science'),
  ('multiple_choice','Which planet has the most moons?','["Mars","Earth","Jupiter","Venus"]','Jupiter',null,'Science'),
  ('multiple_choice','Which mammal can fly?','["Bat","Ostrich","Penguin","Flying squirrel"]','Bat',null,'Science'),
  ('multiple_choice','Which country has the most natural lakes?','["USA","Russia","Canada","Brazil"]','Canada',null,'Geography'),
  ('multiple_choice','Which is the longest river in the world (by most measures)?','["Amazon","Nile","Yangtze","Mississippi"]','Nile',null,'Geography'),
  ('multiple_choice','What is the smallest country in the world?','["Monaco","Vatican City","San Marino","Liechtenstein"]','Vatican City',null,'Geography'),
  ('multiple_choice','Which city is known as the City of Canals?','["Amsterdam","Venice","Bruges","Bangkok"]','Venice',null,'Geography'),
  ('multiple_choice','Which continent has the most countries?','["Asia","Africa","Europe","South America"]','Africa',null,'Geography'),
  ('multiple_choice','Who painted the Mona Lisa?','["Vincent van Gogh","Pablo Picasso","Leonardo da Vinci","Michelangelo"]','Leonardo da Vinci',null,'History'),
  ('multiple_choice','Who was known as the Maid of Orléans?','["Cleopatra","Joan of Arc","Catherine the Great","Boudica"]','Joan of Arc',null,'History'),
  ('multiple_choice','Which empire built the Colosseum?','["Greek","Roman","Ottoman","Persian"]','Roman',null,'History'),
  ('multiple_choice','Who was the British Prime Minister during most of WWII?','["Neville Chamberlain","Winston Churchill","Clement Attlee","Margaret Thatcher"]','Winston Churchill',null,'History'),
  ('multiple_choice','The Magna Carta was signed in which year?','["1215","1066","1492","1314"]','1215',null,'History'),
  ('multiple_choice','Which movie won the first Academy Award for Best Picture?','["Wings","Gone with the Wind","Casablanca","Sunrise"]','Wings',null,'Movies & TV'),
  ('multiple_choice','Who directed "Inception"?','["Christopher Nolan","Steven Spielberg","James Cameron","Ridley Scott"]','Christopher Nolan',null,'Movies & TV'),
  ('multiple_choice','The TV show "Friends" is primarily set in which city?','["Los Angeles","New York City","Chicago","Seattle"]','New York City',null,'Movies & TV'),
  ('multiple_choice','Which film features the quote "I am your father"?','["The Matrix","Star Wars: The Empire Strikes Back","Blade Runner","Terminator 2"]','Star Wars: The Empire Strikes Back',null,'Movies & TV'),
  ('multiple_choice','Who played Jack in "Titanic"?','["Leonardo DiCaprio","Brad Pitt","Tom Cruise","Matt Damon"]','Leonardo DiCaprio',null,'Movies & TV'),
  ('multiple_choice','Which sport is known as "the beautiful game"?','["Rugby","Cricket","Football (Soccer)","Tennis"]','Football (Soccer)',null,'Sports'),
  ('multiple_choice','In tennis, what is a score of zero called?','["Duck","Nil","Love","Blank"]','Love',null,'Sports'),
  ('multiple_choice','How many players are on the field for one soccer team?','["9","10","11","12"]','11',null,'Sports'),
  ('multiple_choice','Which country hosts the Tour de France?','["Italy","France","Spain","Belgium"]','France',null,'Sports'),
  ('multiple_choice','What is the highest possible break in snooker?','["147","155","170","200"]','147',null,'Sports'),
  ('multiple_choice','Which programming language is primarily used for iOS apps?','["Kotlin","Swift","Objective-C#","Dart"]','Swift',null,'Technology'),
  ('multiple_choice','Which company created the TypeScript language?','["Facebook","Google","Microsoft","Oracle"]','Microsoft',null,'Technology'),
  ('multiple_choice','What does SQL stand for?','["Structured Query Language","Simple Query Language","Sequential Query Language","Standard Question Language"]','Structured Query Language',null,'Technology'),
  ('multiple_choice','Which data structure uses FIFO order?','["Stack","Queue","Tree","Graph"]','Queue',null,'Technology'),
  ('multiple_choice','Which algorithm is used for finding the shortest path in a graph with non-negative weights?','["Kruskal","Prim","Dijkstra","Bellman-Ford"]','Dijkstra',null,'Technology'),
  ('multiple_choice','What is the boiling point of water at sea level?','["90°C","95°C","100°C","110°C"]','100°C',null,'Science'),
  ('multiple_choice','Which particle carries a negative charge?','["Proton","Neutron","Electron","Positron"]','Electron',null,'Science'),
  ('multiple_choice','What is the largest internal organ in the human body?','["Heart","Liver","Lungs","Kidneys"]','Liver',null,'Science'),
  ('multiple_choice','What is the most abundant gas in Earth’s atmosphere?','["Oxygen","Nitrogen","Carbon Dioxide","Argon"]','Nitrogen',null,'Science'),
  ('multiple_choice','Which scientist is known for the laws of motion?','["Einstein","Newton","Galileo","Kepler"]','Newton',null,'Science'),
  ('multiple_choice','Which country has the longest coastline?','["Australia","Russia","Canada","Indonesia"]','Canada',null,'Geography'),
  ('multiple_choice','Which country is both in Europe and Asia?','["Spain","Greece","Turkey","Morocco"]','Turkey',null,'Geography'),
  ('multiple_choice','Which city is known as the Eternal City?','["Athens","Rome","Istanbul","Jerusalem"]','Rome',null,'Geography'),
  ('multiple_choice','Which is the largest continent by area?','["Africa","Asia","North America","Antarctica"]','Asia',null,'Geography'),
  ('multiple_choice','Which country is home to the Outback?','["USA","Australia","South Africa","Argentina"]','Australia',null,'Geography'),
  ('multiple_choice','Who was known as the Father of Computers?','["Alan Turing","Charles Babbage","John von Neumann","Ada Lovelace"]','Charles Babbage',null,'Technology'),
  ('multiple_choice','Which markup language is used for structuring data on the web?','["JSON","YAML","XML","CSV"]','XML',null,'Technology'),
  ('multiple_choice','Which sorting algorithm has average time complexity O(n log n)?','["Bubble sort","Insertion sort","Merge sort","Selection sort"]','Merge sort',null,'Technology'),
  ('multiple_choice','Which device measures atmospheric pressure?','["Barometer","Hygrometer","Thermometer","Anemometer"]','Barometer',null,'Science'),
  ('multiple_choice','Which instrument is used to see distant objects in space?','["Microscope","Telescope","Periscope","Spectroscope"]','Telescope',null,'Science'),
  ('multiple_choice','The Battle of Hastings took place in which year?','["1066","1215","1415","1666"]','1066',null,'History'),
  ('multiple_choice','Who was the first woman to fly solo across the Atlantic?','["Amelia Earhart","Sally Ride","Valentina Tereshkova","Bessie Coleman"]','Amelia Earhart',null,'History'),
  ('multiple_choice','Which civilization built Machu Picchu?','["Aztec","Maya","Inca","Olmec"]','Inca',null,'History'),
  ('multiple_choice','Which war was fought between the North and South regions of the United States?','["World War I","Revolutionary War","Civil War","Vietnam War"]','Civil War',null,'History'),
  ('multiple_choice','Who composed the Four Seasons?','["Mozart","Vivaldi","Bach","Beethoven"]','Vivaldi',null,'History'),
  ('multiple_choice','Which actor played Iron Man in the MCU?','["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"]','Robert Downey Jr.',null,'Movies & TV'),
  ('multiple_choice','Which movie features the song "My Heart Will Go On"?','["Titanic","The Bodyguard","Moulin Rouge!","Frozen"]','Titanic',null,'Movies & TV'),
  ('multiple_choice','Which TV series is set in the fictional land of Westeros?','["The Witcher","Game of Thrones","The Mandalorian","Vikings"]','Game of Thrones',null,'Movies & TV'),
  ('multiple_choice','Who directed "Jurassic Park"?','["James Cameron","Steven Spielberg","Peter Jackson","George Lucas"]','Steven Spielberg',null,'Movies & TV'),
  ('multiple_choice','Which movie won Best Picture at the 2020 Oscars?','["1917","Parasite","Joker","Ford v Ferrari"]','Parasite',null,'Movies & TV'),
  ('multiple_choice','How many players are there in a baseball team on the field?','["7","8","9","10"]','9',null,'Sports'),
  ('multiple_choice','In basketball, how many points is a free throw worth?','["1","2","3","4"]','1',null,'Sports'),
  ('multiple_choice','Which country won the FIFA World Cup in 2018?','["Brazil","Germany","France","Croatia"]','France',null,'Sports'),
  ('multiple_choice','In cricket, how many balls make an over?','["5","6","8","10"]','6',null,'Sports'),
  ('multiple_choice','Which sport uses a shuttlecock?','["Table Tennis","Badminton","Squash","Lacrosse"]','Badminton',null,'Sports');

-- Ensure we inserted at least 100 rows overall; this file adds 80+ rows on top of existing ones. Add more if below 100 in your environment.

-- Add 10 more to ensure total of 100 in this seed set
insert into public.questions (type, question_text, options, correct_answer, image_url, category)
values
  ('multiple_choice','Which company created the Android operating system?','["Apple","Microsoft","Google","Nokia"]','Google',null,'Technology'),
  ('multiple_choice','What does GPU stand for?','["Graphics Processing Unit","General Processing Unit","Graphical Performance Unit","Grid Processing Unit"]','Graphics Processing Unit',null,'Technology'),
  ('multiple_choice','Which planet is closest to the Sun?','["Venus","Mercury","Earth","Mars"]','Mercury',null,'Science'),
  ('multiple_choice','Which gas is essential for human respiration?','["Nitrogen","Oxygen","Carbon Dioxide","Helium"]','Oxygen',null,'Science'),
  ('multiple_choice','Which country gifted the Statue of Liberty to the USA?','["United Kingdom","France","Spain","Italy"]','France',null,'History'),
  ('multiple_choice','Who discovered America (widely credited)?','["Leif Erikson","Christopher Columbus","Amerigo Vespucci","James Cook"]','Christopher Columbus',null,'History'),
  ('multiple_choice','Which city hosted the 2012 Summer Olympics?','["Beijing","Rio de Janeiro","London","Athens"]','London',null,'Sports'),
  ('multiple_choice','In golf, what is a score of one under par on a hole called?','["Birdie","Eagle","Bogey","Albatross"]','Birdie',null,'Sports'),
  ('multiple_choice','Which film series features the character Harry Potter?','["The Lord of the Rings","Harry Potter","The Chronicles of Narnia","Percy Jackson"]','Harry Potter',null,'Movies & TV'),
  ('multiple_choice','Who directed "The Godfather"?','["Martin Scorsese","Francis Ford Coppola","Brian De Palma","Stanley Kubrick"]','Francis Ford Coppola',null,'Movies & TV');


